package com.springcloud.example.dynamic.model;

import java.util.ArrayList;
import java.util.List;

public class DayInInstallExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public DayInInstallExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDevpDateIsNull() {
            addCriterion("devp_date is null");
            return (Criteria) this;
        }

        public Criteria andDevpDateIsNotNull() {
            addCriterion("devp_date is not null");
            return (Criteria) this;
        }

        public Criteria andDevpDateEqualTo(Integer value) {
            addCriterion("devp_date =", value, "devpDate");
            return (Criteria) this;
        }

        public Criteria andDevpDateNotEqualTo(Integer value) {
            addCriterion("devp_date <>", value, "devpDate");
            return (Criteria) this;
        }

        public Criteria andDevpDateGreaterThan(Integer value) {
            addCriterion("devp_date >", value, "devpDate");
            return (Criteria) this;
        }

        public Criteria andDevpDateGreaterThanOrEqualTo(Integer value) {
            addCriterion("devp_date >=", value, "devpDate");
            return (Criteria) this;
        }

        public Criteria andDevpDateLessThan(Integer value) {
            addCriterion("devp_date <", value, "devpDate");
            return (Criteria) this;
        }

        public Criteria andDevpDateLessThanOrEqualTo(Integer value) {
            addCriterion("devp_date <=", value, "devpDate");
            return (Criteria) this;
        }

        public Criteria andDevpDateIn(List<Integer> values) {
            addCriterion("devp_date in", values, "devpDate");
            return (Criteria) this;
        }

        public Criteria andDevpDateNotIn(List<Integer> values) {
            addCriterion("devp_date not in", values, "devpDate");
            return (Criteria) this;
        }

        public Criteria andDevpDateBetween(Integer value1, Integer value2) {
            addCriterion("devp_date between", value1, value2, "devpDate");
            return (Criteria) this;
        }

        public Criteria andDevpDateNotBetween(Integer value1, Integer value2) {
            addCriterion("devp_date not between", value1, value2, "devpDate");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeIsNull() {
            addCriterion("devp_citycode is null");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeIsNotNull() {
            addCriterion("devp_citycode is not null");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeEqualTo(String value) {
            addCriterion("devp_citycode =", value, "devpCitycode");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeNotEqualTo(String value) {
            addCriterion("devp_citycode <>", value, "devpCitycode");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeGreaterThan(String value) {
            addCriterion("devp_citycode >", value, "devpCitycode");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeGreaterThanOrEqualTo(String value) {
            addCriterion("devp_citycode >=", value, "devpCitycode");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeLessThan(String value) {
            addCriterion("devp_citycode <", value, "devpCitycode");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeLessThanOrEqualTo(String value) {
            addCriterion("devp_citycode <=", value, "devpCitycode");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeLike(String value) {
            addCriterion("devp_citycode like", value, "devpCitycode");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeNotLike(String value) {
            addCriterion("devp_citycode not like", value, "devpCitycode");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeIn(List<String> values) {
            addCriterion("devp_citycode in", values, "devpCitycode");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeNotIn(List<String> values) {
            addCriterion("devp_citycode not in", values, "devpCitycode");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeBetween(String value1, String value2) {
            addCriterion("devp_citycode between", value1, value2, "devpCitycode");
            return (Criteria) this;
        }

        public Criteria andDevpCitycodeNotBetween(String value1, String value2) {
            addCriterion("devp_citycode not between", value1, value2, "devpCitycode");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameIsNull() {
            addCriterion("devp_cityname is null");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameIsNotNull() {
            addCriterion("devp_cityname is not null");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameEqualTo(String value) {
            addCriterion("devp_cityname =", value, "devpCityname");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameNotEqualTo(String value) {
            addCriterion("devp_cityname <>", value, "devpCityname");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameGreaterThan(String value) {
            addCriterion("devp_cityname >", value, "devpCityname");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameGreaterThanOrEqualTo(String value) {
            addCriterion("devp_cityname >=", value, "devpCityname");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameLessThan(String value) {
            addCriterion("devp_cityname <", value, "devpCityname");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameLessThanOrEqualTo(String value) {
            addCriterion("devp_cityname <=", value, "devpCityname");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameLike(String value) {
            addCriterion("devp_cityname like", value, "devpCityname");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameNotLike(String value) {
            addCriterion("devp_cityname not like", value, "devpCityname");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameIn(List<String> values) {
            addCriterion("devp_cityname in", values, "devpCityname");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameNotIn(List<String> values) {
            addCriterion("devp_cityname not in", values, "devpCityname");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameBetween(String value1, String value2) {
            addCriterion("devp_cityname between", value1, value2, "devpCityname");
            return (Criteria) this;
        }

        public Criteria andDevpCitynameNotBetween(String value1, String value2) {
            addCriterion("devp_cityname not between", value1, value2, "devpCityname");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameIsNull() {
            addCriterion("devp_username is null");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameIsNotNull() {
            addCriterion("devp_username is not null");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameEqualTo(String value) {
            addCriterion("devp_username =", value, "devpUsername");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameNotEqualTo(String value) {
            addCriterion("devp_username <>", value, "devpUsername");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameGreaterThan(String value) {
            addCriterion("devp_username >", value, "devpUsername");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("devp_username >=", value, "devpUsername");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameLessThan(String value) {
            addCriterion("devp_username <", value, "devpUsername");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameLessThanOrEqualTo(String value) {
            addCriterion("devp_username <=", value, "devpUsername");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameLike(String value) {
            addCriterion("devp_username like", value, "devpUsername");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameNotLike(String value) {
            addCriterion("devp_username not like", value, "devpUsername");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameIn(List<String> values) {
            addCriterion("devp_username in", values, "devpUsername");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameNotIn(List<String> values) {
            addCriterion("devp_username not in", values, "devpUsername");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameBetween(String value1, String value2) {
            addCriterion("devp_username between", value1, value2, "devpUsername");
            return (Criteria) this;
        }

        public Criteria andDevpUsernameNotBetween(String value1, String value2) {
            addCriterion("devp_username not between", value1, value2, "devpUsername");
            return (Criteria) this;
        }

        public Criteria andDevpUserIsNull() {
            addCriterion("devp_user is null");
            return (Criteria) this;
        }

        public Criteria andDevpUserIsNotNull() {
            addCriterion("devp_user is not null");
            return (Criteria) this;
        }

        public Criteria andDevpUserEqualTo(Integer value) {
            addCriterion("devp_user =", value, "devpUser");
            return (Criteria) this;
        }

        public Criteria andDevpUserNotEqualTo(Integer value) {
            addCriterion("devp_user <>", value, "devpUser");
            return (Criteria) this;
        }

        public Criteria andDevpUserGreaterThan(Integer value) {
            addCriterion("devp_user >", value, "devpUser");
            return (Criteria) this;
        }

        public Criteria andDevpUserGreaterThanOrEqualTo(Integer value) {
            addCriterion("devp_user >=", value, "devpUser");
            return (Criteria) this;
        }

        public Criteria andDevpUserLessThan(Integer value) {
            addCriterion("devp_user <", value, "devpUser");
            return (Criteria) this;
        }

        public Criteria andDevpUserLessThanOrEqualTo(Integer value) {
            addCriterion("devp_user <=", value, "devpUser");
            return (Criteria) this;
        }

        public Criteria andDevpUserIn(List<Integer> values) {
            addCriterion("devp_user in", values, "devpUser");
            return (Criteria) this;
        }

        public Criteria andDevpUserNotIn(List<Integer> values) {
            addCriterion("devp_user not in", values, "devpUser");
            return (Criteria) this;
        }

        public Criteria andDevpUserBetween(Integer value1, Integer value2) {
            addCriterion("devp_user between", value1, value2, "devpUser");
            return (Criteria) this;
        }

        public Criteria andDevpUserNotBetween(Integer value1, Integer value2) {
            addCriterion("devp_user not between", value1, value2, "devpUser");
            return (Criteria) this;
        }

        public Criteria andDevpInstalltotalIsNull() {
            addCriterion("devp_installtotal is null");
            return (Criteria) this;
        }

        public Criteria andDevpInstalltotalIsNotNull() {
            addCriterion("devp_installtotal is not null");
            return (Criteria) this;
        }

        public Criteria andDevpInstalltotalEqualTo(Integer value) {
            addCriterion("devp_installtotal =", value, "devpInstalltotal");
            return (Criteria) this;
        }

        public Criteria andDevpInstalltotalNotEqualTo(Integer value) {
            addCriterion("devp_installtotal <>", value, "devpInstalltotal");
            return (Criteria) this;
        }

        public Criteria andDevpInstalltotalGreaterThan(Integer value) {
            addCriterion("devp_installtotal >", value, "devpInstalltotal");
            return (Criteria) this;
        }

        public Criteria andDevpInstalltotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("devp_installtotal >=", value, "devpInstalltotal");
            return (Criteria) this;
        }

        public Criteria andDevpInstalltotalLessThan(Integer value) {
            addCriterion("devp_installtotal <", value, "devpInstalltotal");
            return (Criteria) this;
        }

        public Criteria andDevpInstalltotalLessThanOrEqualTo(Integer value) {
            addCriterion("devp_installtotal <=", value, "devpInstalltotal");
            return (Criteria) this;
        }

        public Criteria andDevpInstalltotalIn(List<Integer> values) {
            addCriterion("devp_installtotal in", values, "devpInstalltotal");
            return (Criteria) this;
        }

        public Criteria andDevpInstalltotalNotIn(List<Integer> values) {
            addCriterion("devp_installtotal not in", values, "devpInstalltotal");
            return (Criteria) this;
        }

        public Criteria andDevpInstalltotalBetween(Integer value1, Integer value2) {
            addCriterion("devp_installtotal between", value1, value2, "devpInstalltotal");
            return (Criteria) this;
        }

        public Criteria andDevpInstalltotalNotBetween(Integer value1, Integer value2) {
            addCriterion("devp_installtotal not between", value1, value2, "devpInstalltotal");
            return (Criteria) this;
        }

        public Criteria andAccHomeIsNull() {
            addCriterion("acc_home is null");
            return (Criteria) this;
        }

        public Criteria andAccHomeIsNotNull() {
            addCriterion("acc_home is not null");
            return (Criteria) this;
        }

        public Criteria andAccHomeEqualTo(Integer value) {
            addCriterion("acc_home =", value, "accHome");
            return (Criteria) this;
        }

        public Criteria andAccHomeNotEqualTo(Integer value) {
            addCriterion("acc_home <>", value, "accHome");
            return (Criteria) this;
        }

        public Criteria andAccHomeGreaterThan(Integer value) {
            addCriterion("acc_home >", value, "accHome");
            return (Criteria) this;
        }

        public Criteria andAccHomeGreaterThanOrEqualTo(Integer value) {
            addCriterion("acc_home >=", value, "accHome");
            return (Criteria) this;
        }

        public Criteria andAccHomeLessThan(Integer value) {
            addCriterion("acc_home <", value, "accHome");
            return (Criteria) this;
        }

        public Criteria andAccHomeLessThanOrEqualTo(Integer value) {
            addCriterion("acc_home <=", value, "accHome");
            return (Criteria) this;
        }

        public Criteria andAccHomeIn(List<Integer> values) {
            addCriterion("acc_home in", values, "accHome");
            return (Criteria) this;
        }

        public Criteria andAccHomeNotIn(List<Integer> values) {
            addCriterion("acc_home not in", values, "accHome");
            return (Criteria) this;
        }

        public Criteria andAccHomeBetween(Integer value1, Integer value2) {
            addCriterion("acc_home between", value1, value2, "accHome");
            return (Criteria) this;
        }

        public Criteria andAccHomeNotBetween(Integer value1, Integer value2) {
            addCriterion("acc_home not between", value1, value2, "accHome");
            return (Criteria) this;
        }

        public Criteria andAccTradeIsNull() {
            addCriterion("acc_trade is null");
            return (Criteria) this;
        }

        public Criteria andAccTradeIsNotNull() {
            addCriterion("acc_trade is not null");
            return (Criteria) this;
        }

        public Criteria andAccTradeEqualTo(Integer value) {
            addCriterion("acc_trade =", value, "accTrade");
            return (Criteria) this;
        }

        public Criteria andAccTradeNotEqualTo(Integer value) {
            addCriterion("acc_trade <>", value, "accTrade");
            return (Criteria) this;
        }

        public Criteria andAccTradeGreaterThan(Integer value) {
            addCriterion("acc_trade >", value, "accTrade");
            return (Criteria) this;
        }

        public Criteria andAccTradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("acc_trade >=", value, "accTrade");
            return (Criteria) this;
        }

        public Criteria andAccTradeLessThan(Integer value) {
            addCriterion("acc_trade <", value, "accTrade");
            return (Criteria) this;
        }

        public Criteria andAccTradeLessThanOrEqualTo(Integer value) {
            addCriterion("acc_trade <=", value, "accTrade");
            return (Criteria) this;
        }

        public Criteria andAccTradeIn(List<Integer> values) {
            addCriterion("acc_trade in", values, "accTrade");
            return (Criteria) this;
        }

        public Criteria andAccTradeNotIn(List<Integer> values) {
            addCriterion("acc_trade not in", values, "accTrade");
            return (Criteria) this;
        }

        public Criteria andAccTradeBetween(Integer value1, Integer value2) {
            addCriterion("acc_trade between", value1, value2, "accTrade");
            return (Criteria) this;
        }

        public Criteria andAccTradeNotBetween(Integer value1, Integer value2) {
            addCriterion("acc_trade not between", value1, value2, "accTrade");
            return (Criteria) this;
        }

        public Criteria andInstallYearFinishIsNull() {
            addCriterion("install_year_finish is null");
            return (Criteria) this;
        }

        public Criteria andInstallYearFinishIsNotNull() {
            addCriterion("install_year_finish is not null");
            return (Criteria) this;
        }

        public Criteria andInstallYearFinishEqualTo(Integer value) {
            addCriterion("install_year_finish =", value, "installYearFinish");
            return (Criteria) this;
        }

        public Criteria andInstallYearFinishNotEqualTo(Integer value) {
            addCriterion("install_year_finish <>", value, "installYearFinish");
            return (Criteria) this;
        }

        public Criteria andInstallYearFinishGreaterThan(Integer value) {
            addCriterion("install_year_finish >", value, "installYearFinish");
            return (Criteria) this;
        }

        public Criteria andInstallYearFinishGreaterThanOrEqualTo(Integer value) {
            addCriterion("install_year_finish >=", value, "installYearFinish");
            return (Criteria) this;
        }

        public Criteria andInstallYearFinishLessThan(Integer value) {
            addCriterion("install_year_finish <", value, "installYearFinish");
            return (Criteria) this;
        }

        public Criteria andInstallYearFinishLessThanOrEqualTo(Integer value) {
            addCriterion("install_year_finish <=", value, "installYearFinish");
            return (Criteria) this;
        }

        public Criteria andInstallYearFinishIn(List<Integer> values) {
            addCriterion("install_year_finish in", values, "installYearFinish");
            return (Criteria) this;
        }

        public Criteria andInstallYearFinishNotIn(List<Integer> values) {
            addCriterion("install_year_finish not in", values, "installYearFinish");
            return (Criteria) this;
        }

        public Criteria andInstallYearFinishBetween(Integer value1, Integer value2) {
            addCriterion("install_year_finish between", value1, value2, "installYearFinish");
            return (Criteria) this;
        }

        public Criteria andInstallYearFinishNotBetween(Integer value1, Integer value2) {
            addCriterion("install_year_finish not between", value1, value2, "installYearFinish");
            return (Criteria) this;
        }

        public Criteria andInstallMonthFinishIsNull() {
            addCriterion("install_month_finish is null");
            return (Criteria) this;
        }

        public Criteria andInstallMonthFinishIsNotNull() {
            addCriterion("install_month_finish is not null");
            return (Criteria) this;
        }

        public Criteria andInstallMonthFinishEqualTo(Integer value) {
            addCriterion("install_month_finish =", value, "installMonthFinish");
            return (Criteria) this;
        }

        public Criteria andInstallMonthFinishNotEqualTo(Integer value) {
            addCriterion("install_month_finish <>", value, "installMonthFinish");
            return (Criteria) this;
        }

        public Criteria andInstallMonthFinishGreaterThan(Integer value) {
            addCriterion("install_month_finish >", value, "installMonthFinish");
            return (Criteria) this;
        }

        public Criteria andInstallMonthFinishGreaterThanOrEqualTo(Integer value) {
            addCriterion("install_month_finish >=", value, "installMonthFinish");
            return (Criteria) this;
        }

        public Criteria andInstallMonthFinishLessThan(Integer value) {
            addCriterion("install_month_finish <", value, "installMonthFinish");
            return (Criteria) this;
        }

        public Criteria andInstallMonthFinishLessThanOrEqualTo(Integer value) {
            addCriterion("install_month_finish <=", value, "installMonthFinish");
            return (Criteria) this;
        }

        public Criteria andInstallMonthFinishIn(List<Integer> values) {
            addCriterion("install_month_finish in", values, "installMonthFinish");
            return (Criteria) this;
        }

        public Criteria andInstallMonthFinishNotIn(List<Integer> values) {
            addCriterion("install_month_finish not in", values, "installMonthFinish");
            return (Criteria) this;
        }

        public Criteria andInstallMonthFinishBetween(Integer value1, Integer value2) {
            addCriterion("install_month_finish between", value1, value2, "installMonthFinish");
            return (Criteria) this;
        }

        public Criteria andInstallMonthFinishNotBetween(Integer value1, Integer value2) {
            addCriterion("install_month_finish not between", value1, value2, "installMonthFinish");
            return (Criteria) this;
        }

        public Criteria andInstallWeekFinishIsNull() {
            addCriterion("install_week_finish is null");
            return (Criteria) this;
        }

        public Criteria andInstallWeekFinishIsNotNull() {
            addCriterion("install_week_finish is not null");
            return (Criteria) this;
        }

        public Criteria andInstallWeekFinishEqualTo(Integer value) {
            addCriterion("install_week_finish =", value, "installWeekFinish");
            return (Criteria) this;
        }

        public Criteria andInstallWeekFinishNotEqualTo(Integer value) {
            addCriterion("install_week_finish <>", value, "installWeekFinish");
            return (Criteria) this;
        }

        public Criteria andInstallWeekFinishGreaterThan(Integer value) {
            addCriterion("install_week_finish >", value, "installWeekFinish");
            return (Criteria) this;
        }

        public Criteria andInstallWeekFinishGreaterThanOrEqualTo(Integer value) {
            addCriterion("install_week_finish >=", value, "installWeekFinish");
            return (Criteria) this;
        }

        public Criteria andInstallWeekFinishLessThan(Integer value) {
            addCriterion("install_week_finish <", value, "installWeekFinish");
            return (Criteria) this;
        }

        public Criteria andInstallWeekFinishLessThanOrEqualTo(Integer value) {
            addCriterion("install_week_finish <=", value, "installWeekFinish");
            return (Criteria) this;
        }

        public Criteria andInstallWeekFinishIn(List<Integer> values) {
            addCriterion("install_week_finish in", values, "installWeekFinish");
            return (Criteria) this;
        }

        public Criteria andInstallWeekFinishNotIn(List<Integer> values) {
            addCriterion("install_week_finish not in", values, "installWeekFinish");
            return (Criteria) this;
        }

        public Criteria andInstallWeekFinishBetween(Integer value1, Integer value2) {
            addCriterion("install_week_finish between", value1, value2, "installWeekFinish");
            return (Criteria) this;
        }

        public Criteria andInstallWeekFinishNotBetween(Integer value1, Integer value2) {
            addCriterion("install_week_finish not between", value1, value2, "installWeekFinish");
            return (Criteria) this;
        }

        public Criteria andInstallWeekOnhookIsNull() {
            addCriterion("install_week_onhook is null");
            return (Criteria) this;
        }

        public Criteria andInstallWeekOnhookIsNotNull() {
            addCriterion("install_week_onhook is not null");
            return (Criteria) this;
        }

        public Criteria andInstallWeekOnhookEqualTo(Integer value) {
            addCriterion("install_week_onhook =", value, "installWeekOnhook");
            return (Criteria) this;
        }

        public Criteria andInstallWeekOnhookNotEqualTo(Integer value) {
            addCriterion("install_week_onhook <>", value, "installWeekOnhook");
            return (Criteria) this;
        }

        public Criteria andInstallWeekOnhookGreaterThan(Integer value) {
            addCriterion("install_week_onhook >", value, "installWeekOnhook");
            return (Criteria) this;
        }

        public Criteria andInstallWeekOnhookGreaterThanOrEqualTo(Integer value) {
            addCriterion("install_week_onhook >=", value, "installWeekOnhook");
            return (Criteria) this;
        }

        public Criteria andInstallWeekOnhookLessThan(Integer value) {
            addCriterion("install_week_onhook <", value, "installWeekOnhook");
            return (Criteria) this;
        }

        public Criteria andInstallWeekOnhookLessThanOrEqualTo(Integer value) {
            addCriterion("install_week_onhook <=", value, "installWeekOnhook");
            return (Criteria) this;
        }

        public Criteria andInstallWeekOnhookIn(List<Integer> values) {
            addCriterion("install_week_onhook in", values, "installWeekOnhook");
            return (Criteria) this;
        }

        public Criteria andInstallWeekOnhookNotIn(List<Integer> values) {
            addCriterion("install_week_onhook not in", values, "installWeekOnhook");
            return (Criteria) this;
        }

        public Criteria andInstallWeekOnhookBetween(Integer value1, Integer value2) {
            addCriterion("install_week_onhook between", value1, value2, "installWeekOnhook");
            return (Criteria) this;
        }

        public Criteria andInstallWeekOnhookNotBetween(Integer value1, Integer value2) {
            addCriterion("install_week_onhook not between", value1, value2, "installWeekOnhook");
            return (Criteria) this;
        }

        public Criteria andDevpUpdatetimeIsNull() {
            addCriterion("devp_updatetime is null");
            return (Criteria) this;
        }

        public Criteria andDevpUpdatetimeIsNotNull() {
            addCriterion("devp_updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andDevpUpdatetimeEqualTo(Integer value) {
            addCriterion("devp_updatetime =", value, "devpUpdatetime");
            return (Criteria) this;
        }

        public Criteria andDevpUpdatetimeNotEqualTo(Integer value) {
            addCriterion("devp_updatetime <>", value, "devpUpdatetime");
            return (Criteria) this;
        }

        public Criteria andDevpUpdatetimeGreaterThan(Integer value) {
            addCriterion("devp_updatetime >", value, "devpUpdatetime");
            return (Criteria) this;
        }

        public Criteria andDevpUpdatetimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("devp_updatetime >=", value, "devpUpdatetime");
            return (Criteria) this;
        }

        public Criteria andDevpUpdatetimeLessThan(Integer value) {
            addCriterion("devp_updatetime <", value, "devpUpdatetime");
            return (Criteria) this;
        }

        public Criteria andDevpUpdatetimeLessThanOrEqualTo(Integer value) {
            addCriterion("devp_updatetime <=", value, "devpUpdatetime");
            return (Criteria) this;
        }

        public Criteria andDevpUpdatetimeIn(List<Integer> values) {
            addCriterion("devp_updatetime in", values, "devpUpdatetime");
            return (Criteria) this;
        }

        public Criteria andDevpUpdatetimeNotIn(List<Integer> values) {
            addCriterion("devp_updatetime not in", values, "devpUpdatetime");
            return (Criteria) this;
        }

        public Criteria andDevpUpdatetimeBetween(Integer value1, Integer value2) {
            addCriterion("devp_updatetime between", value1, value2, "devpUpdatetime");
            return (Criteria) this;
        }

        public Criteria andDevpUpdatetimeNotBetween(Integer value1, Integer value2) {
            addCriterion("devp_updatetime not between", value1, value2, "devpUpdatetime");
            return (Criteria) this;
        }

        public Criteria andInstallWeekBackboardIsNull() {
            addCriterion("install_week_backboard is null");
            return (Criteria) this;
        }

        public Criteria andInstallWeekBackboardIsNotNull() {
            addCriterion("install_week_backboard is not null");
            return (Criteria) this;
        }

        public Criteria andInstallWeekBackboardEqualTo(Integer value) {
            addCriterion("install_week_backboard =", value, "installWeekBackboard");
            return (Criteria) this;
        }

        public Criteria andInstallWeekBackboardNotEqualTo(Integer value) {
            addCriterion("install_week_backboard <>", value, "installWeekBackboard");
            return (Criteria) this;
        }

        public Criteria andInstallWeekBackboardGreaterThan(Integer value) {
            addCriterion("install_week_backboard >", value, "installWeekBackboard");
            return (Criteria) this;
        }

        public Criteria andInstallWeekBackboardGreaterThanOrEqualTo(Integer value) {
            addCriterion("install_week_backboard >=", value, "installWeekBackboard");
            return (Criteria) this;
        }

        public Criteria andInstallWeekBackboardLessThan(Integer value) {
            addCriterion("install_week_backboard <", value, "installWeekBackboard");
            return (Criteria) this;
        }

        public Criteria andInstallWeekBackboardLessThanOrEqualTo(Integer value) {
            addCriterion("install_week_backboard <=", value, "installWeekBackboard");
            return (Criteria) this;
        }

        public Criteria andInstallWeekBackboardIn(List<Integer> values) {
            addCriterion("install_week_backboard in", values, "installWeekBackboard");
            return (Criteria) this;
        }

        public Criteria andInstallWeekBackboardNotIn(List<Integer> values) {
            addCriterion("install_week_backboard not in", values, "installWeekBackboard");
            return (Criteria) this;
        }

        public Criteria andInstallWeekBackboardBetween(Integer value1, Integer value2) {
            addCriterion("install_week_backboard between", value1, value2, "installWeekBackboard");
            return (Criteria) this;
        }

        public Criteria andInstallWeekBackboardNotBetween(Integer value1, Integer value2) {
            addCriterion("install_week_backboard not between", value1, value2, "installWeekBackboard");
            return (Criteria) this;
        }

        public Criteria andDevpUpduserIsNull() {
            addCriterion("devp_upduser is null");
            return (Criteria) this;
        }

        public Criteria andDevpUpduserIsNotNull() {
            addCriterion("devp_upduser is not null");
            return (Criteria) this;
        }

        public Criteria andDevpUpduserEqualTo(Integer value) {
            addCriterion("devp_upduser =", value, "devpUpduser");
            return (Criteria) this;
        }

        public Criteria andDevpUpduserNotEqualTo(Integer value) {
            addCriterion("devp_upduser <>", value, "devpUpduser");
            return (Criteria) this;
        }

        public Criteria andDevpUpduserGreaterThan(Integer value) {
            addCriterion("devp_upduser >", value, "devpUpduser");
            return (Criteria) this;
        }

        public Criteria andDevpUpduserGreaterThanOrEqualTo(Integer value) {
            addCriterion("devp_upduser >=", value, "devpUpduser");
            return (Criteria) this;
        }

        public Criteria andDevpUpduserLessThan(Integer value) {
            addCriterion("devp_upduser <", value, "devpUpduser");
            return (Criteria) this;
        }

        public Criteria andDevpUpduserLessThanOrEqualTo(Integer value) {
            addCriterion("devp_upduser <=", value, "devpUpduser");
            return (Criteria) this;
        }

        public Criteria andDevpUpduserIn(List<Integer> values) {
            addCriterion("devp_upduser in", values, "devpUpduser");
            return (Criteria) this;
        }

        public Criteria andDevpUpduserNotIn(List<Integer> values) {
            addCriterion("devp_upduser not in", values, "devpUpduser");
            return (Criteria) this;
        }

        public Criteria andDevpUpduserBetween(Integer value1, Integer value2) {
            addCriterion("devp_upduser between", value1, value2, "devpUpduser");
            return (Criteria) this;
        }

        public Criteria andDevpUpduserNotBetween(Integer value1, Integer value2) {
            addCriterion("devp_upduser not between", value1, value2, "devpUpduser");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameIsNull() {
            addCriterion("devp_updusername is null");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameIsNotNull() {
            addCriterion("devp_updusername is not null");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameEqualTo(String value) {
            addCriterion("devp_updusername =", value, "devpUpdusername");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameNotEqualTo(String value) {
            addCriterion("devp_updusername <>", value, "devpUpdusername");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameGreaterThan(String value) {
            addCriterion("devp_updusername >", value, "devpUpdusername");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameGreaterThanOrEqualTo(String value) {
            addCriterion("devp_updusername >=", value, "devpUpdusername");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameLessThan(String value) {
            addCriterion("devp_updusername <", value, "devpUpdusername");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameLessThanOrEqualTo(String value) {
            addCriterion("devp_updusername <=", value, "devpUpdusername");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameLike(String value) {
            addCriterion("devp_updusername like", value, "devpUpdusername");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameNotLike(String value) {
            addCriterion("devp_updusername not like", value, "devpUpdusername");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameIn(List<String> values) {
            addCriterion("devp_updusername in", values, "devpUpdusername");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameNotIn(List<String> values) {
            addCriterion("devp_updusername not in", values, "devpUpdusername");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameBetween(String value1, String value2) {
            addCriterion("devp_updusername between", value1, value2, "devpUpdusername");
            return (Criteria) this;
        }

        public Criteria andDevpUpdusernameNotBetween(String value1, String value2) {
            addCriterion("devp_updusername not between", value1, value2, "devpUpdusername");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 06 13:59:28 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table r_dayliftinstall_task
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}