package com.springcloud.example.dynamic.model;

public class DayInInstall extends DayInInstallKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.devp_cityname
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private String devpCityname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.devp_username
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private String devpUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.devp_user
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer devpUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.devp_installtotal
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer devpInstalltotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.acc_home
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer accHome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.acc_trade
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer accTrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.install_year_finish
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer installYearFinish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.install_month_finish
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer installMonthFinish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.install_week_finish
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer installWeekFinish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.install_week_onhook
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer installWeekOnhook;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.devp_updatetime
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer devpUpdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.install_week_backboard
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer installWeekBackboard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.devp_upduser
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer devpUpduser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.devp_updusername
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private String devpUpdusername;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.devp_cityname
     *
     * @return the value of r_dayliftinstall_task.devp_cityname
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public String getDevpCityname() {
        return devpCityname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.devp_cityname
     *
     * @param devpCityname the value for r_dayliftinstall_task.devp_cityname
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setDevpCityname(String devpCityname) {
        this.devpCityname = devpCityname == null ? null : devpCityname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.devp_username
     *
     * @return the value of r_dayliftinstall_task.devp_username
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public String getDevpUsername() {
        return devpUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.devp_username
     *
     * @param devpUsername the value for r_dayliftinstall_task.devp_username
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setDevpUsername(String devpUsername) {
        this.devpUsername = devpUsername == null ? null : devpUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.devp_user
     *
     * @return the value of r_dayliftinstall_task.devp_user
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getDevpUser() {
        return devpUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.devp_user
     *
     * @param devpUser the value for r_dayliftinstall_task.devp_user
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setDevpUser(Integer devpUser) {
        this.devpUser = devpUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.devp_installtotal
     *
     * @return the value of r_dayliftinstall_task.devp_installtotal
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getDevpInstalltotal() {
        return devpInstalltotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.devp_installtotal
     *
     * @param devpInstalltotal the value for r_dayliftinstall_task.devp_installtotal
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setDevpInstalltotal(Integer devpInstalltotal) {
        this.devpInstalltotal = devpInstalltotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.acc_home
     *
     * @return the value of r_dayliftinstall_task.acc_home
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getAccHome() {
        return accHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.acc_home
     *
     * @param accHome the value for r_dayliftinstall_task.acc_home
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setAccHome(Integer accHome) {
        this.accHome = accHome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.acc_trade
     *
     * @return the value of r_dayliftinstall_task.acc_trade
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getAccTrade() {
        return accTrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.acc_trade
     *
     * @param accTrade the value for r_dayliftinstall_task.acc_trade
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setAccTrade(Integer accTrade) {
        this.accTrade = accTrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.install_year_finish
     *
     * @return the value of r_dayliftinstall_task.install_year_finish
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getInstallYearFinish() {
        return installYearFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.install_year_finish
     *
     * @param installYearFinish the value for r_dayliftinstall_task.install_year_finish
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setInstallYearFinish(Integer installYearFinish) {
        this.installYearFinish = installYearFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.install_month_finish
     *
     * @return the value of r_dayliftinstall_task.install_month_finish
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getInstallMonthFinish() {
        return installMonthFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.install_month_finish
     *
     * @param installMonthFinish the value for r_dayliftinstall_task.install_month_finish
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setInstallMonthFinish(Integer installMonthFinish) {
        this.installMonthFinish = installMonthFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.install_week_finish
     *
     * @return the value of r_dayliftinstall_task.install_week_finish
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getInstallWeekFinish() {
        return installWeekFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.install_week_finish
     *
     * @param installWeekFinish the value for r_dayliftinstall_task.install_week_finish
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setInstallWeekFinish(Integer installWeekFinish) {
        this.installWeekFinish = installWeekFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.install_week_onhook
     *
     * @return the value of r_dayliftinstall_task.install_week_onhook
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getInstallWeekOnhook() {
        return installWeekOnhook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.install_week_onhook
     *
     * @param installWeekOnhook the value for r_dayliftinstall_task.install_week_onhook
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setInstallWeekOnhook(Integer installWeekOnhook) {
        this.installWeekOnhook = installWeekOnhook;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.devp_updatetime
     *
     * @return the value of r_dayliftinstall_task.devp_updatetime
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getDevpUpdatetime() {
        return devpUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.devp_updatetime
     *
     * @param devpUpdatetime the value for r_dayliftinstall_task.devp_updatetime
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setDevpUpdatetime(Integer devpUpdatetime) {
        this.devpUpdatetime = devpUpdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.install_week_backboard
     *
     * @return the value of r_dayliftinstall_task.install_week_backboard
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getInstallWeekBackboard() {
        return installWeekBackboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.install_week_backboard
     *
     * @param installWeekBackboard the value for r_dayliftinstall_task.install_week_backboard
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setInstallWeekBackboard(Integer installWeekBackboard) {
        this.installWeekBackboard = installWeekBackboard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.devp_upduser
     *
     * @return the value of r_dayliftinstall_task.devp_upduser
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getDevpUpduser() {
        return devpUpduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.devp_upduser
     *
     * @param devpUpduser the value for r_dayliftinstall_task.devp_upduser
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setDevpUpduser(Integer devpUpduser) {
        this.devpUpduser = devpUpduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.devp_updusername
     *
     * @return the value of r_dayliftinstall_task.devp_updusername
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public String getDevpUpdusername() {
        return devpUpdusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.devp_updusername
     *
     * @param devpUpdusername the value for r_dayliftinstall_task.devp_updusername
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setDevpUpdusername(String devpUpdusername) {
        this.devpUpdusername = devpUpdusername == null ? null : devpUpdusername.trim();
    }
}