package com.springcloud.example.dynamic.model;

public class DayInInstallKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.id
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.devp_date
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer devpDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_dayliftinstall_task.devp_citycode
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private String devpCitycode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.id
     *
     * @return the value of r_dayliftinstall_task.id
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.id
     *
     * @param id the value for r_dayliftinstall_task.id
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.devp_date
     *
     * @return the value of r_dayliftinstall_task.devp_date
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getDevpDate() {
        return devpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.devp_date
     *
     * @param devpDate the value for r_dayliftinstall_task.devp_date
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setDevpDate(Integer devpDate) {
        this.devpDate = devpDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_dayliftinstall_task.devp_citycode
     *
     * @return the value of r_dayliftinstall_task.devp_citycode
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public String getDevpCitycode() {
        return devpCitycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_dayliftinstall_task.devp_citycode
     *
     * @param devpCitycode the value for r_dayliftinstall_task.devp_citycode
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setDevpCitycode(String devpCitycode) {
        this.devpCitycode = devpCitycode == null ? null : devpCitycode.trim();
    }
}