package com.springcloud.example.dynamic.model;

public class FileEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.id
     *
     * @mbggenerated Tue Sep 25 13:58:10 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.model
     *
     * @mbggenerated Tue Sep 25 13:58:10 CST 2018
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.name
     *
     * @mbggenerated Tue Sep 25 13:58:10 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_file.file_path
     *
     * @mbggenerated Tue Sep 25 13:58:10 CST 2018
     */
    private String filePath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.id
     *
     * @return the value of t_file.id
     *
     * @mbggenerated Tue Sep 25 13:58:10 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.id
     *
     * @param id the value for t_file.id
     *
     * @mbggenerated Tue Sep 25 13:58:10 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.model
     *
     * @return the value of t_file.model
     *
     * @mbggenerated Tue Sep 25 13:58:10 CST 2018
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.model
     *
     * @param model the value for t_file.model
     *
     * @mbggenerated Tue Sep 25 13:58:10 CST 2018
     */
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.name
     *
     * @return the value of t_file.name
     *
     * @mbggenerated Tue Sep 25 13:58:10 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.name
     *
     * @param name the value for t_file.name
     *
     * @mbggenerated Tue Sep 25 13:58:10 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_file.file_path
     *
     * @return the value of t_file.file_path
     *
     * @mbggenerated Tue Sep 25 13:58:10 CST 2018
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_file.file_path
     *
     * @param filePath the value for t_file.file_path
     *
     * @mbggenerated Tue Sep 25 13:58:10 CST 2018
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }
}