package com.springcloud.example.dynamic.model;

public class SaleAreas {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_areas.ID
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_areas.ParentId
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_areas.Name
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_areas.ShortName
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_areas.MergerShortName
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    private String mergershortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_areas.LevelType
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    private String leveltype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_areas.CityCode
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    private String citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_areas.ZipCode
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_areas.Remark
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_areas.open
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    private Short open;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_areas.longitude
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sale_areas.latitude
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    private Double latitude;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_areas.ID
     *
     * @return the value of sale_areas.ID
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_areas.ID
     *
     * @param id the value for sale_areas.ID
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_areas.ParentId
     *
     * @return the value of sale_areas.ParentId
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_areas.ParentId
     *
     * @param parentid the value for sale_areas.ParentId
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_areas.Name
     *
     * @return the value of sale_areas.Name
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_areas.Name
     *
     * @param name the value for sale_areas.Name
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_areas.ShortName
     *
     * @return the value of sale_areas.ShortName
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_areas.ShortName
     *
     * @param shortname the value for sale_areas.ShortName
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_areas.MergerShortName
     *
     * @return the value of sale_areas.MergerShortName
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public String getMergershortname() {
        return mergershortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_areas.MergerShortName
     *
     * @param mergershortname the value for sale_areas.MergerShortName
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public void setMergershortname(String mergershortname) {
        this.mergershortname = mergershortname == null ? null : mergershortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_areas.LevelType
     *
     * @return the value of sale_areas.LevelType
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public String getLeveltype() {
        return leveltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_areas.LevelType
     *
     * @param leveltype the value for sale_areas.LevelType
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public void setLeveltype(String leveltype) {
        this.leveltype = leveltype == null ? null : leveltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_areas.CityCode
     *
     * @return the value of sale_areas.CityCode
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_areas.CityCode
     *
     * @param citycode the value for sale_areas.CityCode
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode == null ? null : citycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_areas.ZipCode
     *
     * @return the value of sale_areas.ZipCode
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_areas.ZipCode
     *
     * @param zipcode the value for sale_areas.ZipCode
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_areas.Remark
     *
     * @return the value of sale_areas.Remark
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_areas.Remark
     *
     * @param remark the value for sale_areas.Remark
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_areas.open
     *
     * @return the value of sale_areas.open
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public Short getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_areas.open
     *
     * @param open the value for sale_areas.open
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public void setOpen(Short open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_areas.longitude
     *
     * @return the value of sale_areas.longitude
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_areas.longitude
     *
     * @param longitude the value for sale_areas.longitude
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sale_areas.latitude
     *
     * @return the value of sale_areas.latitude
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sale_areas.latitude
     *
     * @param latitude the value for sale_areas.latitude
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
}