package com.springcloud.example.dynamic.model;

import java.util.Date;

public class Task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.id
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.progress_type
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    private Byte progressType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_type
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    private Byte taskType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.screen_type
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    private Byte screenType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.year
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    private Short year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.month
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    private Byte month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.week
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    private Byte week;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.target_num
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    private Integer targetNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.company
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.creator_id
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    private Integer creatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.create_time
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.update_time
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.id
     *
     * @return the value of task.id
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.id
     *
     * @param id the value for task.id
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.progress_type
     *
     * @return the value of task.progress_type
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public Byte getProgressType() {
        return progressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.progress_type
     *
     * @param progressType the value for task.progress_type
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public void setProgressType(Byte progressType) {
        this.progressType = progressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_type
     *
     * @return the value of task.task_type
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public Byte getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_type
     *
     * @param taskType the value for task.task_type
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public void setTaskType(Byte taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.screen_type
     *
     * @return the value of task.screen_type
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public Byte getScreenType() {
        return screenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.screen_type
     *
     * @param screenType the value for task.screen_type
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public void setScreenType(Byte screenType) {
        this.screenType = screenType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.year
     *
     * @return the value of task.year
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public Short getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.year
     *
     * @param year the value for task.year
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public void setYear(Short year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.month
     *
     * @return the value of task.month
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public Byte getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.month
     *
     * @param month the value for task.month
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public void setMonth(Byte month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.week
     *
     * @return the value of task.week
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public Byte getWeek() {
        return week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.week
     *
     * @param week the value for task.week
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public void setWeek(Byte week) {
        this.week = week;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.target_num
     *
     * @return the value of task.target_num
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public Integer getTargetNum() {
        return targetNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.target_num
     *
     * @param targetNum the value for task.target_num
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public void setTargetNum(Integer targetNum) {
        this.targetNum = targetNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.company
     *
     * @return the value of task.company
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.company
     *
     * @param company the value for task.company
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.creator_id
     *
     * @return the value of task.creator_id
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.creator_id
     *
     * @param creatorId the value for task.creator_id
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.create_time
     *
     * @return the value of task.create_time
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.create_time
     *
     * @param createTime the value for task.create_time
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.update_time
     *
     * @return the value of task.update_time
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.update_time
     *
     * @param updateTime the value for task.update_time
     *
     * @mbggenerated Fri Jan 11 15:22:24 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}