package com.springcloud.example.dynamic.model;

public class WeekTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_week_task.task_id
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_week_task.week_id
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer weekId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_week_task.city_code
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_week_task.city_name
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_week_task.in_number
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer inNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_week_task.out_number
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer outNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_week_task.advert_number
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer advertNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_week_task.type
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_week_task.task_id
     *
     * @return the value of r_week_task.task_id
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_week_task.task_id
     *
     * @param taskId the value for r_week_task.task_id
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_week_task.week_id
     *
     * @return the value of r_week_task.week_id
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getWeekId() {
        return weekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_week_task.week_id
     *
     * @param weekId the value for r_week_task.week_id
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setWeekId(Integer weekId) {
        this.weekId = weekId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_week_task.city_code
     *
     * @return the value of r_week_task.city_code
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_week_task.city_code
     *
     * @param cityCode the value for r_week_task.city_code
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_week_task.city_name
     *
     * @return the value of r_week_task.city_name
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_week_task.city_name
     *
     * @param cityName the value for r_week_task.city_name
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_week_task.in_number
     *
     * @return the value of r_week_task.in_number
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getInNumber() {
        return inNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_week_task.in_number
     *
     * @param inNumber the value for r_week_task.in_number
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setInNumber(Integer inNumber) {
        this.inNumber = inNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_week_task.out_number
     *
     * @return the value of r_week_task.out_number
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getOutNumber() {
        return outNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_week_task.out_number
     *
     * @param outNumber the value for r_week_task.out_number
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setOutNumber(Integer outNumber) {
        this.outNumber = outNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_week_task.advert_number
     *
     * @return the value of r_week_task.advert_number
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getAdvertNumber() {
        return advertNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_week_task.advert_number
     *
     * @param advertNumber the value for r_week_task.advert_number
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setAdvertNumber(Integer advertNumber) {
        this.advertNumber = advertNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_week_task.type
     *
     * @return the value of r_week_task.type
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_week_task.type
     *
     * @param type the value for r_week_task.type
     *
     * @mbggenerated Thu Sep 06 13:59:28 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }
}