package com.springcloud.example.dynamic.dao;

import com.springcloud.example.dynamic.model.SaleAreas;
import com.springcloud.example.dynamic.model.SaleAreasExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SaleAreasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_areas
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    int countByExample(SaleAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_areas
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    int deleteByExample(SaleAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_areas
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_areas
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    int insert(SaleAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_areas
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    int insertSelective(SaleAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_areas
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    List<SaleAreas> selectByExample(SaleAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_areas
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    SaleAreas selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_areas
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    int updateByExampleSelective(@Param("record") SaleAreas record, @Param("example") SaleAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_areas
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    int updateByExample(@Param("record") SaleAreas record, @Param("example") SaleAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_areas
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    int updateByPrimaryKeySelective(SaleAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sale_areas
     *
     * @mbggenerated Mon Sep 10 11:28:47 CST 2018
     */
    int updateByPrimaryKey(SaleAreas record);
}