server:
  port: 6688

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3316/springboot?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    password:
    timeout: 8000
    port: 6379
eureka:
  client:
    enabled: false
logging:
  level: debug

#===JWT start===
#JWT\u5B58\u50A8\u7684\u8BF7\u6C42\u5934
jwt.tokenHeader: Authorization
#JWT\u52A0\u89E3\u5BC6\u4F7F\u7528\u7684\u5BC6\u94A5
jwt.secret: mySecret
#JWT\u7684\u8D85\u671F\u9650\u65F6\u95F4(60*60*24)
jwt.expiration: 604800
#JWT\u8D1F\u8F7D\u4E2D\u62FF\u5230\u5F00\u5934
jwt.tokenHead: Bearer
#===JWT end===