server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8
  context-path: /dynamic
spring:
  application:
    name: dynamic
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-request-size: 100Mb
      max-file-size: 100Mb
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3316/report?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
  redis:
      host: 127.0.0.1
      port: 6379
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
      timeout: 2000
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization: true

mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:META-INF/mybatis/mapper/WORKER_NODE.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  type-aliases-package: com.springcloud.example.dynamic.model

mapper:
  not-empty: true
  identity: MYSQL

# pagehelper
pagehelper:
  helper-dialect: MYSQL
  # 参数设置为true时pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页
  reasonable: true
  # 该参数设置为 true 时，如果 pageSize=0 或者 RowBounds.limit = 0 就会查询出全部的结果
  page-size-zero: true
  supportMethodsArguments: true
  params: count=countSql

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/
    register-with-eureka: true
    fetch-registry: true


info:
  name: @project.name@
  description: @project.description@
