server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: dynamic
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3316/report?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka.didispace.com/eureka/
    register-with-eureka: false
    fetch-registry: false

